### ISSUE TITLE
Configuration problem + probable GTFS-RT bug

### ISSUE THREAD

**Issue by matteoferrux** [motis-project/motis#651] opened 2024-11-08 10:03 UTC
I've done a few tests, including installing the latest beta version.

First of all, for some reason (but I think it's due to poor handling on my part), I can't import more than one GTFS stream. I've tried integrating the SNCF feed, but only the Ilevia (Lille) feed works. For Ilevia's RT, when it has the dataset tag “ilevia.gtfs” it can't link me to the pre-existing routes (100% trip_resolve_error) but when I change it and just put “gtfs”, it reduces to 0.9%. Do you perhaps have an explanation that I'm missing?

**Some informations about my MOTIS instance :**
- Version : v2.0.0-beta12
- config.yml : https://pastebin.com/yNVPBEpb
- Ilevia GTFS feed : https://media.ilevia.fr/opendata/gtfs.zip
- SNCF GTFS feed : https://eu.ftp.opendatasoft.com/sncf/gtfs/export-ter-gtfs-last.zip

**Comment by felixguendling** [comment] 2024-11-08 12:22
I cannot reproduce. For what MOTIS supports, everything can be matched.

```
2024-11-08T12:21:13Z | [info][motis.rt                      ] rt update stats for tag=ilevia-gtfs, url=https://proxy.transport.data.gouv.fr/resource/ilevia-lille-gtfs-rt: total_entities=348, total_entities_success=348 (100%)
2024-11-08T12:21:13Z | [info][motis.rt                      ] rt update stats for tag=ilevia-gtfs, url=https://api.mobilille.fr/gtfs/gtfs_rt_mobi.pb: 
2024-11-08T12:21:13Z | [info][motis.rt                      ] rt update stats for tag=sncf-gtfs, url=https://proxy.transport.data.gouv.fr/resource/sncf-ter-gtfs-rt-trip-updates: total_entities=1053, total_entities_success=1041 (98.8604%), unsupported_schedule_relationship=12 (1.1396%)
```

**Comment by felixguendling** [comment] 2024-11-08 13:16
should be fixed with https://github.com/motis-project/motis/commit/a775b73b7f7ee828540200e017fb63f4bf99115d

**Closed by felixguendling** 2024-11-08 13:16 UTC
